# -*- coding: utf-8 -*-
"""FL_FINAL_CODE_5AVG_05_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9MEAo_KQBvhSsQ8i2Mk_Mo3DYZKqoFy
"""

# -*- coding: utf-8 -*-
"""FL_25_02_5TIME_AVG — CORRECTED VERSION

Strategies implemented:
  - FedAvg      : all clients, CE loss, weighted avg aggregation
  - FedProx     : all clients, CE + proximal term, weighted avg aggregation
  - FedNova     : all clients, CE loss, NORMALIZED aggregation (tau_i used)
  - FedCL (MOON): all clients, CE + contrastive loss, weighted avg aggregation
  - PF+CF       : FairFedCS-selected clients (Shi et al., IJCAI 2023) + FedCL training

"""

import copy
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models, transforms, datasets
from torch.utils.data import DataLoader, Subset
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix
)
import random
import os
import time
import json

# ==============================
# CONFIG
# ==============================
BASE_SEED = 42                 # base random seed for reproducibility
NUM_RUNS = 5                # total independent experiment runs
NUM_CLIENTS = 5                # total FL clients
NUM_SELECTED_CLIENTS = 3       # clients selected per round (ONLY for PF+CF)
NUM_ROUNDS = 50                 # number of federated rounds
LOCAL_EPOCHS = 2               # local training epochs per client
BATCH_SIZE = 128                 # batch size for dataloaders
LEARNING_RATE = 1e-4           # optimizer learning rate
MU_PROX = 0.01                 # FedProx proximal weight (lower for deep networks)
MU = 0.5                       # FedCL contrastive weight
TAU = 0.5                      # temperature for contrastive loss
PROJ_DIM = 256                 # projection head output dimension
DROPOUT_RATE = 0.5             # dropout probability in model
BETA = 0.5                     # Dirichlet split concentration parameter

# --- FairFedCS hyperparameters (Shi et al., IJCAI 2023) ---
SIGMA = 1.0                    # trade-off: performance (reputation) vs fairness (queue)
FAIRFED_TARGET = 0.5           # target participation rate c_i per round (fairness goal)

DATASET_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "kaggle_6k_dataset")

# --- Paths & Directories ---
RESULTS_DIR = "results"                                  # Folder to store CSV results
CHECKPOINTS_DIR = "checkpoints"                          # Folder for crash-recovery checkpoints

os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(CHECKPOINTS_DIR, exist_ok=True)

CSV_FILE = os.path.join(RESULTS_DIR, "detailed_fl_results.csv")  # output results file
CHECKPOINT_FILE = os.path.join(CHECKPOINTS_DIR, "training_state.pt")  # checkpoint file

# ==============================
# GPU / DEVICE SETUP
# ==============================
if torch.cuda.is_available():
    DEVICE = torch.device("cuda")
    # Set for deterministic behavior on GPU
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
else:
    DEVICE = torch.device("cpu")

# Number of dataloader workers — use 4 on GPU machines, 0 on CPU-only
NUM_WORKERS = 4 if torch.cuda.is_available() else 0
PIN_MEMORY = torch.cuda.is_available()   # pin_memory speeds up CPU→GPU transfer

def print_device_info():
    """Print comprehensive device/GPU diagnostics at startup."""
    print("=" * 60)
    print("DEVICE DIAGNOSTICS")
    print("=" * 60)
    print(f"  PyTorch version  : {torch.__version__}")
    print(f"  CUDA available   : {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"  CUDA version     : {torch.version.cuda}")
        print(f"  cuDNN version    : {torch.backends.cudnn.version()}")
        print(f"  GPU count        : {torch.cuda.device_count()}")
        for i in range(torch.cuda.device_count()):
            props = torch.cuda.get_device_properties(i)
            print(f"  GPU {i}            : {props.name}")
            print(f"    Memory         : {props.total_memory / 1024**3:.1f} GB")
            print(f"    Compute Cap.   : {props.major}.{props.minor}")
    else:
        print("  *** WARNING: CUDA NOT AVAILABLE — RUNNING ON CPU ***")
        print("  Check: 1) NVIDIA driver installed  2) CUDA toolkit version")
        print("         3) PyTorch installed with CUDA support")
        print("         (pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121)")
    print(f"  Using device     : {DEVICE}")
    print(f"  DataLoader workers: {NUM_WORKERS}")
    print(f"  pin_memory       : {PIN_MEMORY}")
    print("=" * 60)

    # Quick GPU sanity check
    if torch.cuda.is_available():
        t = torch.zeros(1, device=DEVICE)
        print(f"  Sanity check     : tensor on {t.device} ✓")
        del t
        torch.cuda.empty_cache()
    print()


# ==============================
# TRANSFORMS
# ==============================
transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=3),               # convert to 3-ch
    transforms.Resize((224, 224)),                             # resize
    transforms.RandomHorizontalFlip(),                         # augmentation
    transforms.RandomRotation(15),
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.ColorJitter(brightness=0.1, contrast=0.1),
    transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 1.0)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225]),
])

# ==============================
# DIRICHLET SPLIT (Non-IID)
# ==============================
def dirichlet_split(dataset, num_clients, beta):
    """Split dataset among clients using Dirichlet distribution."""
    if isinstance(dataset, Subset):
        labels = np.array(dataset.dataset.targets)[dataset.indices]
        base_dataset = dataset.dataset
        indices_ref = dataset.indices
    else:
        labels = np.array(dataset.targets)
        base_dataset = dataset
        indices_ref = np.arange(len(dataset))

    client_indices = [[] for _ in range(num_clients)]

    for cls in np.unique(labels):
        cls_idx = np.where(labels == cls)[0]
        np.random.shuffle(cls_idx)
        proportions = np.random.dirichlet(np.repeat(beta, num_clients))
        splits = (np.cumsum(proportions) * len(cls_idx)).astype(int)[:-1]
        cls_splits = np.split(cls_idx, splits)

        for i, s in enumerate(cls_splits):
            client_indices[i].extend(indices_ref[j] for j in s)

    return [Subset(base_dataset, idxs) for idxs in client_indices]

# ==============================
# MODEL
# ==============================
class ShuffleNetFedCL(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        backbone = models.shufflenet_v2_x0_5(
            weights=models.ShuffleNet_V2_X0_5_Weights.DEFAULT
        )
        self.backbone = nn.Sequential(*list(backbone.children())[:-1])
        num_ftrs = backbone.fc.in_features

        self.dropout = nn.Dropout(DROPOUT_RATE)
        self.proj = nn.Sequential(                  # projection head (contrastive)
            nn.Linear(num_ftrs, PROJ_DIM),
            nn.ReLU(),
            nn.Linear(PROJ_DIM, PROJ_DIM)
        )
        self.cls = nn.Linear(num_ftrs, num_classes) # classification head

    def forward(self, x, return_features=False):
        x = self.backbone(x).mean([2, 3])           # global avg pooling
        feat = self.dropout(x)
        proj = self.proj(feat)
        out = self.cls(feat)
        if return_features:
            return out, proj, feat
        return out

# ==============================
# CONTRASTIVE LOSS (MOON-style)
# ==============================
def contrastive_loss(v, vg, vl):
    """
    v  : current local model projection
    vg : global (previous round) projection  — POSITIVE
    vl : previous local model projection     — NEGATIVE
    """
    v, vg, vl = map(lambda x: F.normalize(x, dim=-1), [v, vg, vl])
    sg = torch.sum(v * vg, dim=-1) / TAU        # sim(current, global)
    sl = torch.sum(v * vl, dim=-1) / TAU        # sim(current, prev_local)
    return (-torch.log(torch.exp(sg) /
            (torch.exp(sg) + torch.exp(sl) + 1e-8))).mean()

# ==============================
# LOCAL TRAINERS
# ==============================

def local_train_fedavg(model, loader):
    """FedAvg local training: CE loss only."""
    ce = nn.CrossEntropyLoss()
    opt = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    model.train()
    for _ in range(LOCAL_EPOCHS):
        for x, y in loader:
            x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE, non_blocking=True)
            opt.zero_grad()
            loss = ce(model(x), y)
            loss.backward()
            opt.step()
    return model


def local_train_fedprox(model, global_model, loader):
    """FedProx local training: CE + proximal term (mu/2)||w - w_global||^2."""
    ce = nn.CrossEntropyLoss()
    opt = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    # Freeze a snapshot of global params (detached clones, kept on DEVICE)
    global_params = [p.detach().clone() for p in global_model.parameters()]
    model.train()
    for _ in range(LOCAL_EPOCHS):
        for x, y in loader:
            x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE, non_blocking=True)
            opt.zero_grad()
            loss = ce(model(x), y)
            prox = sum(((w - w_t) ** 2).sum()
                       for w, w_t in zip(model.parameters(), global_params))
            (loss + (MU_PROX / 2) * prox).backward()
            opt.step()
    return model


def local_train_fednova(model, loader):
    """FedNova local training: CE loss, returns (model, tau_i)."""
    ce = nn.CrossEntropyLoss()
    opt = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    tau_i = 0                   # count local gradient steps
    model.train()
    for _ in range(LOCAL_EPOCHS):
        for x, y in loader:
            x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE, non_blocking=True)
            opt.zero_grad()
            ce(model(x), y).backward()
            opt.step()
            tau_i += 1
    return model, tau_i


def local_train_fedcl(model, g_prev, l_prev, loader):
    """FedCL / MOON local training: CE + mu * contrastive_loss."""
    ce = nn.CrossEntropyLoss()
    opt = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    g_prev.eval()               # deterministic projections (no dropout noise)
    l_prev.eval()
    model.train()
    for _ in range(LOCAL_EPOCHS):
        for x, y in loader:
            x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE, non_blocking=True)
            opt.zero_grad()
            with torch.no_grad():
                _, vg, _ = g_prev(x, True)    # global projection (positive)
                _, vl, _ = l_prev(x, True)    # prev-local projection (negative)
            out, v, _ = model(x, True)        # current model outputs
            loss = ce(out, y) + MU * contrastive_loss(v, vg, vl)
            loss.backward()
            opt.step()
    return model

# ==============================
# AGGREGATION — Weighted Average (FedAvg / FedProx / FedCL)
# ==============================
def aggregate(global_m, locals_, sizes):
    """Standard weighted aggregation: w = sum(n_i/n * w_i)."""
    new = copy.deepcopy(global_m.state_dict())
    total = sum(sizes)
    for k in new:
        if new[k].dtype.is_floating_point:
            new[k] = sum(
                locals_[i].state_dict()[k].to(DEVICE) * (sizes[i] / total)
                for i in range(len(locals_))
            )
    global_m.load_state_dict(new)
    global_m.to(DEVICE)   # ensure model is on GPU after loading state
    return global_m

# ==============================
# AGGREGATION — FedNova (Normalized Averaging)
# ==============================
def aggregate_fednova(global_m, locals_, taus, sizes):
    """
    FedNova normalized aggregation (Wang et al., NeurIPS 2020).

    d_i   = (w_global - w_local_i) / tau_i      — normalized pseudo-gradient
    p_i   = n_i / n_total                        — data-proportional weight
    tau_eff = sum(p_i * tau_i)                   — effective number of steps
    w_new = w_global - tau_eff * sum(p_i * d_i)  — updated global model
    """
    total = sum(sizes)
    weights = [s / total for s in sizes]

    # Effective number of local steps
    tau_eff = sum(w * t for w, t in zip(weights, taus))

    global_sd = global_m.state_dict()
    new_sd = copy.deepcopy(global_sd)

    for k in new_sd:
        if new_sd[k].dtype.is_floating_point:
            # Ensure all tensors are on DEVICE for computation
            g_param = global_sd[k].to(DEVICE)
            # Weighted sum of normalized pseudo-gradients
            delta = sum(
                weights[i] * (g_param - locals_[i].state_dict()[k].to(DEVICE)) / taus[i]
                for i in range(len(locals_))
            )
            new_sd[k] = g_param - tau_eff * delta

    global_m.load_state_dict(new_sd)
    global_m.to(DEVICE)   # ensure model is on GPU after loading state
    return global_m

# ==============================
# FAIRFEDCS CLIENT SELECTION (Shi et al., IJCAI 2023)
# ==============================

def compute_client_reputation(global_model, local_model, val_loader):
    """
    Evaluate a client's contribution quality by comparing global-only
    accuracy vs accuracy after incorporating the client update.
    Returns 1 (positive contribution) or 0 (negative contribution).
    """
    global_model.eval()
    local_model.eval()
    g_correct, l_correct, total = 0, 0, 0
    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE, non_blocking=True)
            g_correct += (torch.argmax(global_model(x), 1) == y).sum().item()
            l_correct += (torch.argmax(local_model(x), 1) == y).sum().item()
            total += y.size(0)
    # Positive if local model improved over global
    return 1 if l_correct >= g_correct else 0


def fairfedcs_select(queues, reputations, num_select):
    """
    FairFedCS client selection (Shi et al., IJCAI 2023).

    Client Selection Index:  CSI_i = SIGMA * R_i + Q_i
      - R_i = alpha_i / (alpha_i + beta_i)   (Beta Reputation System)
      - Q_i = virtual queue (higher → client has been under-served)
      - SIGMA controls performance vs fairness trade-off

    Select top-k clients with highest CSI.
    """
    num_clients = len(queues)
    csi = np.zeros(num_clients)
    for i in range(num_clients):
        R_i = reputations[i]       # already computed: alpha/(alpha+beta)
        Q_i = queues[i]
        csi[i] = SIGMA * R_i + Q_i
    selected = np.argsort(csi)[-num_select:]
    return selected


def fairfedcs_update_queues(queues, selected_indices, num_clients):
    """
    Virtual queue update rule (Lyapunov-based):
      Q_i(t+1) = max( Q_i(t) - x_i(t) + c_i, 0 )

    Where:
      x_i(t) = 1 if client i was selected, else 0
      c_i    = FAIRFED_TARGET (target participation rate)
    """
    selected_set = set(selected_indices)
    for i in range(num_clients):
        x_i = 1.0 if i in selected_set else 0.0
        queues[i] = max(queues[i] - x_i + FAIRFED_TARGET, 0.0)
    return queues


def fairfedcs_update_reputation(alphas, betas, client_idx, contribution):
    """
    Beta Reputation System (BRS) update:
      If contribution == 1 (positive):  alpha_i += 1
      If contribution == 0 (negative):  beta_i  += 1
      Reputation R_i = alpha_i / (alpha_i + beta_i)
    """
    if contribution == 1:
        alphas[client_idx] += 1
    else:
        betas[client_idx] += 1
    return alphas[client_idx] / (alphas[client_idx] + betas[client_idx])

# ==============================
# EVALUATION
# ==============================
def evaluate(model, loader, num_classes):
    """Compute accuracy, precision, recall, F1, specificity."""
    y_true, y_pred = [], []
    model.eval()
    with torch.no_grad():
        for x, y in loader:
            x = x.to(DEVICE, non_blocking=True)
            p = torch.argmax(model(x), 1).cpu().numpy()
            y_pred.extend(p)
            y_true.extend(y.numpy())

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='macro', zero_division=0)
    rec = recall_score(y_true, y_pred, average='macro', zero_division=0)
    f1 = f1_score(y_true, y_pred, average='macro', zero_division=0)

    cm = confusion_matrix(y_true, y_pred)
    specs = []
    for i in range(num_classes):
        tn = cm.sum() - (cm[i, :].sum() + cm[:, i].sum() - cm[i, i])
        fp = cm[:, i].sum() - cm[i, i]
        specs.append(tn / (tn + fp + 1e-8))

    return acc, prec, rec, f1, np.mean(specs)


def evaluate_with_predictions(model, loader, num_classes):
    """
    Full evaluation that captures raw labels, predicted labels, and
    class-wise softmax probability scores (needed for real CMs and ROC curves).
    Returns: (acc, prec, rec, f1, spec, y_true_arr, y_pred_arr, y_scores_arr)
    """
    y_true, y_pred, y_scores = [], [], []
    model.eval()
    with torch.no_grad():
        for x, y in loader:
            x = x.to(DEVICE, non_blocking=True)
            logits = model(x)
            probs  = torch.softmax(logits, dim=1).cpu().numpy()
            preds  = torch.argmax(logits, dim=1).cpu().numpy()
            y_pred.extend(preds)
            y_true.extend(y.numpy())
            y_scores.extend(probs)

    y_true   = np.array(y_true)
    y_pred   = np.array(y_pred)
    y_scores = np.array(y_scores)

    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='macro', zero_division=0)
    rec  = recall_score(y_true, y_pred, average='macro', zero_division=0)
    f1   = f1_score(y_true, y_pred, average='macro', zero_division=0)

    cm = confusion_matrix(y_true, y_pred)
    specs = []
    for i in range(num_classes):
        tn = cm.sum() - (cm[i, :].sum() + cm[:, i].sum() - cm[i, i])
        fp = cm[:, i].sum() - cm[i, i]
        specs.append(tn / (tn + fp + 1e-8))

    return acc, prec, rec, f1, np.mean(specs), y_true, y_pred, y_scores

# ==============================
# CHECKPOINTING (Crash Recovery)
# ==============================
def save_checkpoint(filepath, run, rnd, models_dict, prev_cl, prev_pf,
                    ff_state, all_test_runs, all_times_runs, csv_position):
    """Save full training state to disk for crash recovery."""
    state = {
        'run': run,
        'round': rnd,
        'models': {k: m.state_dict() for k, m in models_dict.items()},
        'prev_cl': [m.state_dict() for m in prev_cl],
        'prev_pf': [m.state_dict() for m in prev_pf],
        'ff_queues': ff_state['queues'].tolist(),
        'ff_alphas': ff_state['alphas'].tolist(),
        'ff_betas': ff_state['betas'].tolist(),
        'ff_reps': ff_state['reps'].tolist(),
        'all_test_runs': [(
            {k: list(v) for k, v in d.items()}
        ) for d in all_test_runs],
        'all_times_runs': all_times_runs,
        'csv_position': csv_position,
    }
    tmp = filepath + ".tmp"
    torch.save(state, tmp)
    os.replace(tmp, filepath)
    print(f"  [CKPT] Saved checkpoint: run={run}, round={rnd}")


def load_checkpoint(filepath, num_classes):
    """Load checkpoint. Returns state dict or None if no checkpoint exists."""
    if not os.path.exists(filepath):
        return None
    try:
        state = torch.load(filepath, map_location=DEVICE, weights_only=False)
        print(f"  [CKPT] Loaded checkpoint: run={state['run']}, round={state['round']}")
        return state
    except Exception as e:
        print(f"  [CKPT] Corrupt checkpoint, starting fresh: {e}")
        return None


# ==============================
# MAIN
# ==============================
def main():

    # ===== STEP 1: Print device diagnostics =====
    print_device_info()

    print(f"Number_of_Rounds = {NUM_ROUNDS}")
    print(f"Number_of_Runs = {NUM_RUNS}")
    print(f"Number_of_Total_Clients = {NUM_CLIENTS}")
    print(f"Number_of_Selected_Clients (PF+CF only) = {NUM_SELECTED_CLIENTS}")

    # Load datasets
    train_dataset = datasets.ImageFolder(
        os.path.join(DATASET_PATH, "train"), transform=transform)
    test_dataset = datasets.ImageFolder(
        os.path.join(DATASET_PATH, "test"), transform=transform)
    num_classes = len(train_dataset.classes)

    # ===== Try to load checkpoint for crash recovery =====
    ckpt = load_checkpoint(CHECKPOINT_FILE, num_classes)
    resume_run = 1
    resume_round = 1
    all_test_runs = []
    all_times_runs = []

    if ckpt is not None:
        resume_run = ckpt['run']
        resume_round = ckpt['round'] + 1  # start AFTER the last saved round
        all_test_runs = [
            {k: tuple(v) for k, v in d.items()}
            for d in ckpt.get('all_test_runs', [])
        ]
        all_times_runs = ckpt.get('all_times_runs', [])
        # If we finished all rounds of a run, move to next run
        if resume_round > NUM_ROUNDS:
            resume_run += 1
            resume_round = 1
        print(f"  [CKPT] Resuming from Run {resume_run}, Round {resume_round}")
        csv_mode = "a"  # append to existing CSV
    else:
        csv_mode = "w"  # fresh start

    with open(CSV_FILE, csv_mode) as f:

        # CSV header (only on fresh start)
        if csv_mode == "w":
            f.write(f"Number_of_Rounds,{NUM_ROUNDS}\n")
            f.write(f"Number_of_Runs,{NUM_RUNS}\n")
            f.write(f"Number_of_Total_Clients,{NUM_CLIENTS}\n")
            f.write(f"Number_of_Selected_Clients_PF_CF,{NUM_SELECTED_CLIENTS}\n\n")
            f.flush()

        # ================= RUN LOOP =================
        final_preds = {}   # filled in the last run; used for IEEE plots
        class_names = []   # filled in the last run
        for run in range(1, NUM_RUNS + 1):

            # Skip runs already completed (from checkpoint)
            if run < resume_run:
                continue

            print(f"\n================ RUN {run} / {NUM_RUNS} ================")

            seed = BASE_SEED + run
            random.seed(seed)
            np.random.seed(seed)
            torch.manual_seed(seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed(seed)
                torch.cuda.manual_seed_all(seed)   # for multi-GPU

            # Non-IID client data split
            client_sets = dirichlet_split(train_dataset, NUM_CLIENTS, BETA)
            loaders = [
                DataLoader(
                    ds, BATCH_SIZE, shuffle=True,
                    num_workers=NUM_WORKERS,
                    pin_memory=PIN_MEMORY,
                    persistent_workers=(NUM_WORKERS > 0)
                )
                for ds in client_sets
            ]
            sizes = [len(ds) for ds in client_sets]
            val_loader = DataLoader(
                test_dataset, BATCH_SIZE, shuffle=False,
                num_workers=NUM_WORKERS,
                pin_memory=PIN_MEMORY,
                persistent_workers=(NUM_WORKERS > 0)
            )

            # ===== One global model per strategy =====
            g_avg  = ShuffleNetFedCL(num_classes).to(DEVICE)  # FedAvg
            g_prox = copy.deepcopy(g_avg)                      # FedProx
            g_nova = copy.deepcopy(g_avg)                      # FedNova
            g_cl   = copy.deepcopy(g_avg)                      # FedCL
            g_pf   = copy.deepcopy(g_avg)                      # PF+CF

            # Previous-round local models for contrastive learning
            prev_cl = [copy.deepcopy(g_cl) for _ in range(NUM_CLIENTS)]
            prev_pf = [copy.deepcopy(g_pf) for _ in range(NUM_CLIENTS)]

            # --- FairFedCS state initialization (Shi et al., IJCAI 2023) ---
            ff_queues = np.zeros(NUM_CLIENTS)          # virtual queues Q_i
            ff_alphas = np.ones(NUM_CLIENTS)           # BRS alpha (positive)
            ff_betas  = np.ones(NUM_CLIENTS)           # BRS beta  (negative)
            ff_reps   = np.full(NUM_CLIENTS, 0.5)      # initial reputation = 0.5

            # --- Restore model states from checkpoint if resuming this run ---
            start_round = 1
            if ckpt is not None and run == resume_run:
                start_round = resume_round
                models_sd = ckpt['models']
                g_avg.load_state_dict(models_sd['g_avg'])
                g_prox.load_state_dict(models_sd['g_prox'])
                g_nova.load_state_dict(models_sd['g_nova'])
                g_cl.load_state_dict(models_sd['g_cl'])
                g_pf.load_state_dict(models_sd['g_pf'])
                for i, sd in enumerate(ckpt['prev_cl']):
                    prev_cl[i].load_state_dict(sd)
                for i, sd in enumerate(ckpt['prev_pf']):
                    prev_pf[i].load_state_dict(sd)
                ff_queues = np.array(ckpt['ff_queues'])
                ff_alphas = np.array(ckpt['ff_alphas'])
                ff_betas  = np.array(ckpt['ff_betas'])
                ff_reps   = np.array(ckpt['ff_reps'])
                print(f"  [CKPT] Models restored for Run {run}, starting at Round {start_round}")
                ckpt = None  # consumed, don't restore again


            # ================= ROUND LOOP =================
            for rnd in range(start_round, NUM_ROUNDS + 1):

                print(f"\n---- Round {rnd} ----")
                print(f"{'Technique':<12} {'Acc':<8} {'Prec':<8} "
                      f"{'Recall':<8} {'F1':<8} {'Spec':<8} {'Time(s)':<8}")
                print("-" * 65)

                all_clients = list(range(NUM_CLIENTS))  # ALL clients (no selection)

                # --- FairFedCS selection for PF+CF ---
                sel_fair = fairfedcs_select(
                    ff_queues, ff_reps, NUM_SELECTED_CLIENTS
                )

                # --- Timing dict to store per-technique time ---
                times = {}

                # ---------- FedAvg (ALL clients, no selection) ----------
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                t0 = time.time()
                locals_avg = []
                for i in all_clients:
                    local_m = copy.deepcopy(g_avg)
                    local_m = local_train_fedavg(local_m, loaders[i])
                    locals_avg.append(local_m)
                g_avg = aggregate(g_avg, locals_avg, sizes)
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                times["FedAvg"] = time.time() - t0
                # Free local models to save GPU memory
                del locals_avg
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

                # ---------- FedProx (ALL clients, no selection) ----------
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                t0 = time.time()
                locals_prox = []
                for i in all_clients:
                    local_m = copy.deepcopy(g_prox)
                    local_m = local_train_fedprox(local_m, g_prox, loaders[i])
                    locals_prox.append(local_m)
                g_prox = aggregate(g_prox, locals_prox, sizes)
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                times["FedProx"] = time.time() - t0
                del locals_prox
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

                # ---------- FedNova (ALL clients, NORMALIZED aggregation) ----------
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                t0 = time.time()
                locals_nova = []
                taus_nova = []
                for i in all_clients:
                    local_m = copy.deepcopy(g_nova)
                    local_m, tau_i = local_train_fednova(local_m, loaders[i])
                    locals_nova.append(local_m)
                    taus_nova.append(tau_i)
                g_nova = aggregate_fednova(
                    g_nova, locals_nova, taus_nova, sizes
                )
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                times["FedNova"] = time.time() - t0
                del locals_nova
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

                # ---------- FedCL / MOON (ALL clients, no selection) ----------
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                t0 = time.time()
                locals_cl = []
                for i in all_clients:
                    local_m = copy.deepcopy(g_cl)
                    local_m = local_train_fedcl(
                        local_m, g_cl, prev_cl[i], loaders[i]
                    )
                    locals_cl.append(local_m)
                    prev_cl[i] = copy.deepcopy(local_m)   # update prev local
                g_cl = aggregate(g_cl, locals_cl, sizes)
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                times["FedCL"] = time.time() - t0
                del locals_cl
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

                # ---------- PF+CF: FedCL + FairFedCS Client Selection ----------
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                t0 = time.time()
                locals_pf = []
                for i in sel_fair:
                    local_m = copy.deepcopy(g_pf)         # copy PF+CF global
                    local_m = local_train_fedcl(
                        local_m, g_pf, prev_pf[i], loaders[i]
                    )
                    locals_pf.append(local_m)
                    prev_pf[i] = copy.deepcopy(local_m)   # update prev local

                    # --- BRS reputation update ---
                    contrib = compute_client_reputation(
                        g_pf, local_m, val_loader
                    )
                    ff_reps[i] = fairfedcs_update_reputation(
                        ff_alphas, ff_betas, i, contrib
                    )

                g_pf = aggregate(
                    g_pf, locals_pf, [sizes[i] for i in sel_fair]
                )

                # --- Update virtual queues after aggregation ---
                ff_queues = fairfedcs_update_queues(
                    ff_queues, sel_fair, NUM_CLIENTS
                )
                if torch.cuda.is_available():
                    torch.cuda.synchronize()
                times["PF+CF"] = time.time() - t0
                del locals_pf
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

                # ===== Round metrics (evaluated on test set) =====
                round_metrics = {
                    "FedAvg":  evaluate(g_avg,  val_loader, num_classes),
                    "FedProx": evaluate(g_prox, val_loader, num_classes),
                    "FedNova": evaluate(g_nova, val_loader, num_classes),
                    "FedCL":   evaluate(g_cl,   val_loader, num_classes),
                    "PF+CF":   evaluate(g_pf,   val_loader, num_classes),
                }

                for tech, vals in round_metrics.items():
                    print(f"{tech:<12} {vals[0]:.4f}  {vals[1]:.4f}  "
                          f"{vals[2]:.4f}  {vals[3]:.4f}  {vals[4]:.4f}  "
                          f"{times[tech]:.2f}")

                # CSV — round results (flushed to disk for real-time viewing)
                f.write(f"run,{run}\n")
                f.write(f"train_round,{rnd}\n")
                f.write("Technique,Accuracy,Precision,Recall,F1,Specificity,Time(s)\n")
                for tech, v in round_metrics.items():
                    f.write(f"{tech},{v[0]:.4f},{v[1]:.4f},"
                            f"{v[2]:.4f},{v[3]:.4f},{v[4]:.4f},"
                            f"{times[tech]:.2f}\n")
                f.write("\n")
                f.flush()  # flush to disk so CSV is viewable in real-time

                # --- Save checkpoint after every round ---
                save_checkpoint(
                    CHECKPOINT_FILE, run, rnd,
                    {'g_avg': g_avg, 'g_prox': g_prox, 'g_nova': g_nova,
                     'g_cl': g_cl, 'g_pf': g_pf},
                    prev_cl, prev_pf,
                    {'queues': ff_queues, 'alphas': ff_alphas,
                     'betas': ff_betas, 'reps': ff_reps},
                    all_test_runs, all_times_runs,
                    csv_position=f.tell()
                )

            # ================= TEST (after all rounds) =================
            print(f"\n---- TEST (Run {run} Final) ----")
            print(f"{'Technique':<12} {'Acc':<8} {'Prec':<8} "
                  f"{'Recall':<8} {'F1':<8} {'Spec':<8} {'Time(s)':<8}")
            print("-" * 65)

            test_metrics = {
                "FedAvg":  evaluate(g_avg,  val_loader, num_classes),
                "FedProx": evaluate(g_prox, val_loader, num_classes),
                "FedNova": evaluate(g_nova, val_loader, num_classes),
                "FedCL":   evaluate(g_cl,   val_loader, num_classes),
                "PF+CF":   evaluate(g_pf,   val_loader, num_classes),
            }

            all_test_runs.append(test_metrics)
            all_times_runs.append(dict(times))   # store this run's times

            for tech, vals in test_metrics.items():
                print(f"{tech:<12} {vals[0]:.4f}  {vals[1]:.4f}  "
                      f"{vals[2]:.4f}  {vals[3]:.4f}  {vals[4]:.4f}  "
                      f"{times[tech]:.2f}")

            # CSV — test results
            f.write(f"run,{run}\n")
            f.write("test_final\n")
            f.write("Technique,Accuracy,Precision,Recall,F1,Specificity,Time(s)\n")
            for tech, v in test_metrics.items():
                f.write(f"{tech},{v[0]:.4f},{v[1]:.4f},"
                        f"{v[2]:.4f},{v[3]:.4f},{v[4]:.4f},"
                        f"{times[tech]:.2f}\n")
            f.write("\n")
            f.flush()  # flush to disk for real-time viewing

            # ── Collect real predictions from LAST run for IEEE plots ──
            if run == NUM_RUNS:
                print("\nCollecting final predictions for IEEE-quality plots...")
                class_names = list(train_dataset.classes)
                for tech_name, mdl in [
                    ("FedAvg",  g_avg),
                    ("FedProx", g_prox),
                    ("FedNova", g_nova),
                    ("FedCL",   g_cl),
                    ("FairCL",  g_pf),
                ]:
                    _, _, _, _, _, yt, yp, ys = evaluate_with_predictions(
                        mdl, val_loader, num_classes
                    )
                    final_preds[tech_name] = {
                        "y_true":   yt,
                        "y_pred":   yp,
                        "y_scores": ys,
                    }
                    print(f"    Collected predictions: {tech_name}")

            # Free models at end of run to reclaim GPU memory
            del g_avg, g_prox, g_nova, g_cl, g_pf
            del prev_cl, prev_pf
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            # Reset start_round for next run (only matters on resume)
            start_round = 1

        # ================= FINAL AVERAGE ACROSS RUNS =================
        # Average times across all runs
        all_times_avg = {}
        for tech in all_times_runs[0].keys():
            all_times_avg[tech] = np.mean([t[tech] for t in all_times_runs])

        f.write("FINAL_AVERAGE_TEST\n")
        f.write("Technique,Accuracy,Precision,Recall,F1,Specificity,Time(s)\n")

        for tech in all_test_runs[0].keys():
            avg = np.mean([run_d[tech] for run_d in all_test_runs], axis=0)
            f.write(f"{tech},{avg[0]:.4f},{avg[1]:.4f},"
                    f"{avg[2]:.4f},{avg[3]:.4f},{avg[4]:.4f},"
                    f"{all_times_avg[tech]:.2f}\n")

    print(f"\nDone! Results saved to: {CSV_FILE}")

    # --- Delete checkpoint on successful completion ---
    if os.path.exists(CHECKPOINT_FILE):
        os.remove(CHECKPOINT_FILE)
        print("  [CKPT] Training complete. Checkpoint file removed.")
    
    # Generate final IEEE-quality plots
    print("\nGenerating IEEE-quality evaluation plots...")
    generate_plots(CSV_FILE, final_preds, class_names)


# ==============================
# PLOTTING MODULE  (IEEE-quality)
# ==============================
def generate_plots(results_csv_path, final_preds, class_names):
    """
    Generates IEEE Transaction-quality evaluation plots from REAL model predictions.

    Outputs
    -------
    confusion_matrices/<tech>_cm.png  — class-wise normalised confusion matrix
    roc_curves/<tech>_roc.png         — per-class + macro-avg ROC for each technique
    roc_curves/combined_roc.png       — all techniques macro-avg on one plot
    comparison_graph/metric_comparison.png — grouped bar chart of metrics
    """
    import os
    import numpy as np
    import pandas as pd
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import seaborn as sns
    from sklearn.metrics import (
        confusion_matrix, roc_curve, auc
    )
    from sklearn.preprocessing import label_binarize

    # ------------------------------------------------------------------
    # IEEE rcParams — double-column width ≈ 7.16", single ≈ 3.5"
    # ------------------------------------------------------------------
    plt.rcParams.update({
        'font.family':        'DejaVu Serif',
        'font.size':          10,
        'axes.titlesize':     11,
        'axes.titleweight':   'bold',
        'axes.labelsize':     10,
        'axes.labelweight':   'bold',
        'xtick.labelsize':    8,
        'ytick.labelsize':    8,
        'legend.fontsize':    8,
        'legend.framealpha':  0.85,
        'figure.dpi':         300,
        'savefig.dpi':        300,
        'savefig.bbox':       'tight',
        'lines.linewidth':    1.5,
        'axes.spines.top':    False,
        'axes.spines.right':  False,
    })

    # ------------------------------------------------------------------
    # Folder creation
    # ------------------------------------------------------------------
    for folder in ["confusion_matrices", "roc_curves", "comparison_graph"]:
        os.makedirs(folder, exist_ok=True)

    if not final_preds or not class_names:
        print("  [WARN] No prediction data available — skipping IEEE plots.")
        return

    n_classes    = len(class_names)
    classes_idx  = list(range(n_classes))

    # Short display names (≤14 chars) to keep axis neat
    short_names  = [cn.replace('_', ' ')[:14] for cn in class_names]

    TECH_COLORS = {
        'FedAvg':  '#1f77b4',
        'FedProx': '#d62728',
        'FedNova': '#2ca02c',
        'FedCL':   '#ff7f0e',
        'FairCL':  '#9467bd',
    }
    TECH_MARKERS = {
        'FedAvg':  'o',
        'FedProx': 's',
        'FedNova': '^',
        'FedCL':   'D',
        'FairCL':  'v',
    }

    # ================================================================
    # A.  CONFUSION MATRICES  (one per technique, class-wise)
    # ================================================================
    print("\n[1/3] Generating confusion matrices...")

    for tech, data in final_preds.items():
        y_true = data['y_true']
        y_pred = data['y_pred']

        cm_raw  = confusion_matrix(y_true, y_pred, labels=classes_idx)
        row_sum = cm_raw.sum(axis=1, keepdims=True).astype(float)
        cm_norm = np.where(row_sum > 0, cm_raw / row_sum, 0.0)   # row-normalised

        n  = n_classes
        fw = max(6.0, n * 0.85)   # figure width scales with class count
        fh = max(5.0, n * 0.75)

        fig, ax = plt.subplots(figsize=(fw, fh))

        im = ax.imshow(cm_norm, interpolation='nearest', cmap='Blues',
                       vmin=0.0, vmax=1.0, aspect='auto')
        cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        cbar.set_label('Row-Normalised Proportion', fontsize=9)
        cbar.ax.tick_params(labelsize=8)
        cbar.set_ticks([0.0, 0.25, 0.50, 0.75, 1.0])

        # Cell annotations: percentage on top line, raw count below
        thresh = 0.55
        for i in range(n):
            for j in range(n):
                val   = cm_norm[i, j]
                count = cm_raw[i, j]
                color = 'white' if val > thresh else 'black'
                ax.text(j, i,
                        f'{val*100:.1f}%\n({count})',
                        ha='center', va='center',
                        fontsize=max(5, 8 - n // 4),
                        color=color, fontweight='bold')

        ticks = np.arange(n)
        ax.set_xticks(ticks)
        ax.set_xticklabels(short_names, rotation=45, ha='right', fontsize=max(6, 9 - n // 5))
        ax.set_yticks(ticks)
        ax.set_yticklabels(short_names, fontsize=max(6, 9 - n // 5))

        ax.set_xlabel('Predicted Label')
        ax.set_ylabel('True Label')
        ax.set_title(f'Confusion Matrix — {tech}', pad=12)

        # Fine grid lines between cells
        for edge in np.arange(-0.5, n, 1):
            ax.axhline(edge, color='white', linewidth=0.5)
            ax.axvline(edge, color='white', linewidth=0.5)

        plt.tight_layout()
        fn = tech.lower().replace('+', '').replace(' ', '_')
        out = f"confusion_matrices/{fn}_cm.png"
        plt.savefig(out, dpi=300)
        plt.close()
        print(f"    Saved: {out}")

    # ================================================================
    # B.  ROC CURVES — per technique  (one-vs-rest, per class + macro)
    # ================================================================
    print("\n[2/3] Generating per-technique ROC curves...")

    # Colour cycle for individual classes inside each ROC plot
    cls_cmap   = plt.cm.tab20
    cls_colors = [cls_cmap(i / max(n_classes, 1)) for i in range(n_classes)]
    ls_cycle   = ['-', '--', '-.', ':', (0, (3, 1, 1, 1)), (0, (5, 2))]

    macro_aucs = {}   # store for combined plot

    for tech, data in final_preds.items():
        y_true   = data['y_true']
        y_scores = data['y_scores']

        # Binary-encode labels
        if n_classes == 2:
            y_bin = np.zeros((len(y_true), 2))
            y_bin[np.arange(len(y_true)), y_true] = 1
        else:
            y_bin = label_binarize(y_true, classes=classes_idx)

        fig, ax = plt.subplots(figsize=(6.5, 5.5))
        ax.plot([0, 1], [0, 1], 'k--', lw=1.0, label='Chance (AUC = 0.500)',
                alpha=0.6)

        fprs_all, tprs_all, aucs_all = {}, {}, {}

        for i in range(n_classes):
            fpr_i, tpr_i, _ = roc_curve(y_bin[:, i], y_scores[:, i])
            auc_i            = auc(fpr_i, tpr_i)
            fprs_all[i] = fpr_i
            tprs_all[i] = tpr_i
            aucs_all[i] = auc_i
            ax.plot(fpr_i, tpr_i,
                    color=cls_colors[i],
                    lw=1.1, alpha=0.65,
                    linestyle=ls_cycle[i % len(ls_cycle)],
                    label=f'{short_names[i]} (AUC={auc_i:.3f})')

        # Macro-average
        all_fpr  = np.unique(np.concatenate([fprs_all[i] for i in range(n_classes)]))
        mean_tpr = np.zeros_like(all_fpr)
        for i in range(n_classes):
            mean_tpr += np.interp(all_fpr, fprs_all[i], tprs_all[i])
        mean_tpr /= n_classes
        macro_auc = auc(all_fpr, mean_tpr)
        macro_aucs[tech] = (all_fpr, mean_tpr, macro_auc)

        ax.plot(all_fpr, mean_tpr,
                color=TECH_COLORS.get(tech, 'black'),
                lw=2.5, linestyle='-',
                label=f'Macro-avg (AUC={macro_auc:.3f})')

        ax.set_xlim([0.0, 1.0])
        ax.set_ylim([0.0, 1.02])
        ax.set_xlabel('False Positive Rate (1 - Specificity)')
        ax.set_ylabel('True Positive Rate (Sensitivity)')
        ax.set_title(f'ROC Curve — {tech}')
        ax.legend(loc='lower right', fontsize=7,
                  ncol=1 if n_classes <= 8 else 2)
        ax.grid(True, linestyle='--', alpha=0.35, color='grey')

        plt.tight_layout()
        fn  = tech.lower().replace('+', '').replace(' ', '_')
        out = f"roc_curves/{fn}_roc.png"
        plt.savefig(out, dpi=300)
        plt.close()
        print(f"    Saved: {out}")

    # ================================================================
    # C.  COMBINED ROC  (macro-avg of all 5 techniques on one plot)
    # ================================================================
    print("\n[3/3] Generating combined ROC comparison...")
    fig, ax = plt.subplots(figsize=(6.5, 5.5))
    ax.plot([0, 1], [0, 1], 'k--', lw=1.0, label='Chance (AUC = 0.500)', alpha=0.6)

    for tech, (all_fpr, mean_tpr, mac_auc) in macro_aucs.items():
        ax.plot(all_fpr, mean_tpr,
                color=TECH_COLORS.get(tech, 'grey'),
                lw=2.0,
                marker=TECH_MARKERS.get(tech, 'o'),
                markevery=0.15,
                markersize=5,
                label=f'{tech} (AUC={mac_auc:.3f})')

    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.02])
    ax.set_xlabel('False Positive Rate (1 - Specificity)')
    ax.set_ylabel('True Positive Rate (Sensitivity)')
    ax.set_title('Macro-Average ROC Curve — All Techniques')
    ax.legend(loc='lower right', fontsize=9)
    ax.grid(True, linestyle='--', alpha=0.35, color='grey')

    plt.tight_layout()
    plt.savefig("roc_curves/combined_roc.png", dpi=300)
    plt.close()
    print("    Saved: roc_curves/combined_roc.png")

    # ================================================================
    # D.  METRIC COMPARISON BAR CHART  (from CSV averages)
    # ================================================================
    try:
        df = pd.read_csv(
            results_csv_path,
            names=['Technique', 'Accuracy', 'Precision', 'Recall', 'F1',
                   'Specificity', 'Time'],
            sep=',', on_bad_lines='skip', engine='python'
        )
        techs_order = ["FedAvg", "FedProx", "FedNova", "FedCL", "PF+CF"]
        df['Technique_clean'] = df['Technique'].astype(str).str.strip()
        df_m   = df[df['Technique_clean'].isin(techs_order)].copy()
        df_fin = df_m.tail(5).copy()
        df_fin.reset_index(drop=True, inplace=True)
        for col in ['Accuracy', 'Precision', 'Recall', 'F1', 'Specificity']:
            df_fin[col] = pd.to_numeric(df_fin[col], errors='coerce')
        df_fin['Technique_clean'] = df_fin['Technique_clean'].apply(
            lambda x: 'FairCL' if x == 'PF+CF' else x)

        df_bar = df_fin[['Technique_clean', 'Accuracy', 'Precision',
                          'Recall', 'F1']].copy()
        df_melt = df_bar.melt(id_vars='Technique_clean',
                               var_name='Metric', value_name='Score')

        palette = {'Accuracy': '#1f77b4', 'Precision': '#ff7f0e',
                   'Recall':   '#2ca02c', 'F1':        '#d62728'}

        fig, ax = plt.subplots(figsize=(8, 5))
        sns.barplot(data=df_melt, x='Technique_clean', y='Score',
                    hue='Metric', palette=palette, ax=ax,
                    edgecolor='white', linewidth=0.6)
        ax.set_title('Performance Comparison of FL Techniques')
        ax.set_xlabel('Technique')
        ax.set_ylabel('Score')
        ax.set_ylim(0, 1.12)
        for bar in ax.patches:
            h = bar.get_height()
            if h > 0:
                ax.text(bar.get_x() + bar.get_width() / 2,
                        h + 0.01, f'{h:.3f}',
                        ha='center', va='bottom', fontsize=6, rotation=90)
        ax.legend(title='Metric', bbox_to_anchor=(1.01, 1), loc='upper left')
        ax.grid(axis='y', linestyle='--', alpha=0.4)
        plt.tight_layout()
        plt.savefig("comparison_graph/metric_comparison.png", dpi=300)
        plt.close()
        print("    Saved: comparison_graph/metric_comparison.png")
    except Exception as e:
        print(f"  [WARN] Bar chart skipped: {e}")

    print("\n✓ All IEEE-quality plots generated successfully.")
    print("  ├── confusion_matrices/   (one per technique, class-wise)")
    print("  ├── roc_curves/           (per-technique + combined)")
    print("  └── comparison_graph/     (grouped bar chart)")


if __name__ == "__main__":
    main()